---
title: "README"
author: "Ben Cortes"
date: "October 2, 2018"
output: html_document
---

Load tidyverse

```{r}
library(tidyverse)
```

Downloaded fang_et_al_genotypes.txt and SNP_position.txt to the project folder and renamed them.

```{r}
download.file("https://raw.githubusercontent.com/EEOB-BioData/BCB546X-Fall2018/master/assignments/UNIX_Assignment/fang_et_al_genotypes.txt", destfile = "data/genotypes.txt")

download.file("https://raw.githubusercontent.com/EEOB-BioData/BCB546X-Fall2018/master/assignments/UNIX_Assignment/snp_position.txt", destfile = "data/SNPs.txt")
```
Inspected file structures
  file.info
    size - size of file in bytes
    isdir - whether or not file is directory
    mtime - last time file modified
    ctime - "last status change"
    atime - last accession time
    
```{r}
as.tibble(file.info("data/genotypes.txt"))[,c(1,2,4:6)]
as.tibble(file.info("data/SNPs.txt"))[,c(1,2,4:6)]
```


```{r}
genotypes <- read_tsv("data/genotypes.txt")
snps <- read_tsv("data/SNPs.txt")
```












